/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sdp.prac2;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.util.*;

class AppTest {

    @Test void methodTest() {
        //Arrange
        SimpleFunctions simFuncts = new SimpleFunctions();
        List<Integer> data = new ArrayList<>();
        List<Integer> indexs = new ArrayList<>();
        
        data.add(2);
        indexs.add(0);
        data.add(4);
        indexs.add(1);
        data.add(5);
        indexs.add(2);
        data.add(8);
        indexs.add(3);
 
        int expected = 19;
        //Act
        int result = simFuncts.Task1(data, indexs);
        //Assert
        assertEquals(expected, result);

    }
}
